import differential_geometry_immersions_minimal_prescribed_theorem_canonical_lane_mathlib.GateLemmas
import differential_geometry_immersions_minimal_prescribed_theorem_canonical_lane_mathlib.FinalTheorem
